# Generated by Django 6.1 on 2026-09-09 06:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_category', models.CharField(choices=[('RECYCLE', 'Recyclable'), ('BIO', 'Biodegradable / Compost'), ('RDF', 'Refuse Derived Fuel'), ('REJECT', 'Non-processable / Needs Manual Review')], max_length=20)),
                ('decision_confidence', models.FloatField(default=0.0)),
                ('decision_breakdown', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='detection.wasteimage')),
                ('simulated_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='analysis.simulatedreading')),
            ],
            options={
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['final_category', 'processed_at'], name='waste_recor_final_c_8888ea_idx')],
            },
        ),
    ]
