# Generated by Django 6.1 on 2026-09-09 06:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='waste_images/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('UPLOAD', 'File Upload'), ('WEBCAM', 'Browser Webcam Snapshot'), ('SIMULATED', 'Manual Simulation, No Image')], default='UPLOAD', max_length=20)),
                ('detected_material', models.CharField(choices=[('PLASTIC', 'Plastic'), ('PAPER', 'Paper / Cardboard'), ('METAL', 'Metal'), ('GLASS', 'Glass'), ('ORGANIC', 'Organic / Food Waste'), ('TEXTILE', 'Textile / Cloth'), ('E_WASTE', 'Electronic Waste'), ('MIXED', 'Mixed / Unidentified')], default='MIXED', max_length=20)),
                ('detection_confidence', models.FloatField(default=0.0)),
                ('raw_model_output', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
