# Generated by Django 6.1 on 2026-09-12 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_tag', models.CharField(max_length=50, unique=True)),
                ('architecture', models.CharField(default='YOLOv8-WasteChakra + Optical Spatial Clustering', max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('accuracy', models.FloatField(default=92.5)),
                ('mAP_50', models.FloatField(default=0.895)),
                ('f1_score', models.FloatField(default=0.908)),
                ('total_samples_trained', models.IntegerField(default=0)),
                ('trained_categories', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='wasteimage',
            name='source',
            field=models.CharField(choices=[('UPLOAD', 'File Upload'), ('WEBCAM', 'Browser Webcam Snapshot'), ('SIMULATED', 'Manual Simulation, No Image'), ('INSPECTION_OVERLAY', 'Plant Optical Inspection Scanner')], default='UPLOAD', max_length=20),
        ),
        migrations.CreateModel(
            name='AITrainingSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='training_dataset/%Y/%m/%d/')),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('source', models.CharField(choices=[('CITIZEN_REPORT', 'Citizen Waste Report'), ('COLLECTOR_PROOF', 'Collector Pickup Proof'), ('INSPECTION_SCAN', 'Plant Optical Inspection'), ('COMMUNITY_UPLOAD', 'Community Direct Upload'), ('ADMIN_IMPORT', 'Admin Dataset Import')], default='CITIZEN_REPORT', max_length=30)),
                ('predicted_category', models.CharField(default='MIXED', max_length=30)),
                ('verified_category', models.CharField(blank=True, default='', max_length=30)),
                ('confidence', models.FloatField(default=0.85)),
                ('bounding_boxes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified for Training'), ('REJECTED', 'Rejected / Blurry'), ('IN_TRAINING_SET', 'Queued in Active Batch'), ('TRAINED', 'Model Trained')], default='PENDING_REVIEW', max_length=30)),
                ('quality_score', models.FloatField(default=0.92)),
                ('eco_credits_awarded', models.IntegerField(default=5)),
                ('source_reference_id', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributed_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITrainingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Training in Progress'), ('VALIDATING', 'Validating Checkpoints'), ('COMPLETED', 'Completed & Evaluated'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('total_epochs', models.IntegerField(default=20)),
                ('current_epoch', models.IntegerField(default=0)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('samples_count', models.IntegerField(default=0)),
                ('batch_size', models.IntegerField(default=16)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('current_loss', models.FloatField(default=0.0)),
                ('val_loss', models.FloatField(default=0.0)),
                ('val_mAP', models.FloatField(default=0.0)),
                ('metrics_history', models.JSONField(blank=True, default=list)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_training_jobs', to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_jobs', to='detection.modelversion')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
