/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container-high": "#e2ebe1",
        "on-secondary-container": "#427000",
        "on-tertiary-fixed": "#00210f",
        "on-error": "#ffffff",
        "surface-container-low": "#edf6ec",
        "on-error-container": "#93000a",
        "surface-bright": "#f3fcf2",
        "surface": "#f3fcf2",
        "surface-container-highest": "#dce5db",
        "on-tertiary-fixed-variant": "#254f35",
        "secondary-container": "#abf854",
        "secondary-fixed": "#abf854",
        "primary": "#00180b",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#424843",
        "primary-fixed": "#c8ebd1",
        "on-background": "#161d18",
        "background": "#f3fcf2",
        "secondary-fixed-dim": "#90db39",
        "on-secondary-fixed-variant": "#2d5000",
        "inverse-primary": "#accfb6",
        "on-secondary-fixed": "#0f2000",
        "surface-variant": "#dce5db",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#022111",
        "on-surface": "#161d18",
        "error": "#ba1a1a",
        "surface-tint": "#466551",
        "inverse-on-surface": "#eaf3e9",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#a3d1b0",
        "on-tertiary-container": "#6d997a",
        "on-primary-container": "#769780",
        "tertiary-fixed": "#bfeecb",
        "inverse-surface": "#2a322c",
        "on-secondary": "#ffffff",
        "surface-container": "#e7f0e6",
        "primary-fixed-dim": "#accfb6",
        "outline-variant": "#c2c8c1",
        "outline": "#727972",
        "on-primary-fixed-variant": "#2f4d3a",
        "tertiary-container": "#012f18",
        "surface-dim": "#d4dcd3",
        "primary-container": "#0f2e1d",
        "tertiary": "#00180a",
        "secondary": "#3d6a00",
        "error-container": "#ffdad6",
        "text-muted": "#424843",
        "border-industrial": "#dce5db",
        "grid-line": "rgba(22, 29, 24, 0.05)",
        "forest": "#0d2a1a"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "space-md": "1rem",
        "gutter": "1.5rem",
        "space-sm": "0.75rem",
        "space-2xl": "3rem",
        "space-xxs": "0.25rem",
        "space-xl": "2rem",
        "space-4xl": "6rem",
        "container-max": "80rem",
        "space-xs": "0.5rem",
        "space-3xl": "4rem",
        "space-lg": "1.5rem",
        "margin-mobile": "20px",
        "margin-desktop": "64px"
      },
      "fontFamily": {
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "eyebrow-tag": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Playfair Display", "serif"],
        "display-hero-mobile": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "stat-counter": ["Plus Jakarta Sans", "sans-serif"],
        "stat-counter-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "mono-data": ["Plus Jakarta Sans", "sans-serif"]
      },
      "fontSize": {
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "eyebrow-tag": ["12px", { "lineHeight": "16px", "letterSpacing": "0.12em", "fontWeight": "700" }],
        "body-md": ["15px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "display-hero-mobile": ["38px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "title-md": ["18px", { "lineHeight": "26px", "fontWeight": "600" }],
        "headline-md": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "stat-counter": ["56px", { "lineHeight": "60px", "letterSpacing": "-0.03em", "fontWeight": "800" }],
        "headline-lg-mobile": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "stat-counter-mobile": ["40px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "display-hero": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["44px", { "lineHeight": "52px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
        "headline-sm": ["22px", { "lineHeight": "30px", "fontWeight": "700" }],
        "display-lg": ["72px", { "lineHeight": "80px", "letterSpacing": "-0.04em", "fontWeight": "600" }],
        "mono-data": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}