# Generated by Django 6.1 on 2026-09-09 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_id', models.CharField(max_length=20, unique=True)),
                ('pickup_type', models.CharField(choices=[('HOME', 'Home'), ('BUSINESS', 'Business'), ('SOCIETY', 'Society')], default='HOME', max_length=20)),
                ('waste_type', models.CharField(choices=[('RECYCLABLES', 'Recyclables'), ('ORGANIC', 'Organic'), ('MIXED', 'Mixed Waste'), ('BULK', 'Bulk Waste'), ('E_WASTE', 'E-Waste'), ('OTHER', 'Other')], default='MIXED', max_length=30)),
                ('estimated_quantity', models.CharField(blank=True, default='', max_length=20)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, default='', max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('ARRIVED', 'Arrived'), ('COLLECTED', 'Collected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('actual_weight_kg', models.FloatField(blank=True, null=True)),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='pickup_proof/before/%Y/%m/%d/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='pickup_proof/after/%Y/%m/%d/')),
                ('collector_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collector_pickups', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WastePassport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passport_id', models.CharField(max_length=20, unique=True)),
                ('origin', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('SOCIETY', 'Society')], default='RESIDENTIAL', max_length=20)),
                ('input_weight_kg', models.FloatField(default=0.0)),
                ('plastic_recovered_kg', models.FloatField(default=0.0)),
                ('paper_recovered_kg', models.FloatField(default=0.0)),
                ('organic_recovered_kg', models.FloatField(default=0.0)),
                ('metal_recovered_kg', models.FloatField(default=0.0)),
                ('rdf_produced_kg', models.FloatField(default=0.0)),
                ('inert_kg', models.FloatField(default=0.0)),
                ('residual_kg', models.FloatField(default=0.0)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pickup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='pickups.pickup')),
            ],
        ),
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='waste_reports/%Y/%m/%d/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('waste_type', models.CharField(choices=[('MIXED', 'Mixed Waste'), ('PLASTIC', 'Plastic'), ('ORGANIC', 'Organic'), ('PAPER', 'Paper'), ('METAL', 'Metal'), ('TEXTILE', 'Textile'), ('E_WASTE', 'E-Waste'), ('CONSTRUCTION', 'Construction Waste'), ('BULK', 'Bulk Waste'), ('HAZARDOUS', 'Hazardous Waste')], default='MIXED', max_length=30)),
                ('estimated_quantity', models.CharField(choices=[('<5', '<5 kg'), ('5-20', '5-20 kg'), ('20-50', '20-50 kg'), ('50-100', '50-100 kg'), ('100+', '100+ kg')], default='5-20', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('urgency', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('PICKUP_SCHEDULED', 'Pickup Scheduled'), ('COLLECTED', 'Collected'), ('IN_TRANSIT', 'In Transit'), ('AT_FACILITY', 'At Facility'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='REPORTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pickup',
            name='waste_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='pickups.wastereport'),
        ),
    ]
