# Generated by Django 6.1.1 on 2026-09-12 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='offered_collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickup',
            name='rejected_collectors',
            field=models.ManyToManyField(blank=True, related_name='rejected_pickups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('OFFERED', 'Offered to Collector'), ('CONFIRMED', 'Confirmed'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('ARRIVED', 'Arrived'), ('COLLECTED', 'Collected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20),
        ),
    ]
