# Generated by Django 6.1.1 on 2026-09-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickups', '0002_pickup_offered_collector_pickup_rejected_collectors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='waste_type',
            field=models.CharField(choices=[('MIXED', 'Mixed Waste'), ('PLASTIC', 'Plastic'), ('ORGANIC', 'Organic'), ('PAPER', 'Paper'), ('METAL', 'Metal'), ('TEXTILE', 'Textile'), ('E_WASTE', 'E-Waste'), ('CONSTRUCTION', 'Construction Waste'), ('BULK', 'Bulk Waste'), ('HAZARDOUS', 'Hazardous Waste'), ('RECYCLABLES', 'Recyclables'), ('OTHER', 'Other')], default='MIXED', max_length=30),
        ),
    ]
