# Generated by Django 6.1.1 on 2026-09-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_address_line1_userprofile_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
