# Generated by Django 6.1.1 on 2026-09-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_type',
            field=models.CharField(blank=True, default='VAN', max_length=20),
        ),
    ]
