# Generated by Django 6.1 on 2026-09-13 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_collectorprofile_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardCatalogItem',
            fields=[
                ('id', models.CharField(help_text='Unique slug or identifier, e.g. eco-voucher-50', max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('cost', models.PositiveIntegerField(help_text='Chakra points required to redeem')),
                ('category', models.CharField(choices=[('VOUCHER', 'Eco Voucher'), ('MERCHANDISE', 'Sustainable Merchandise'), ('DONATION', 'Green Cause & Tree Planting'), ('EXPERIENCE', 'Workshop & Pass')], default='VOUCHER', max_length=30)),
                ('icon', models.CharField(default='card_giftcard', help_text='Lucide/Material icon name', max_length=50)),
                ('image_url', models.URLField(blank=True, default='')),
                ('stock', models.IntegerField(default=100, help_text='-1 for unlimited stock')),
                ('partner_name', models.CharField(blank=True, default='WasteChakra Green Partner', max_length=100)),
                ('terms', models.TextField(blank=True, default='Valid for 90 days from redemption. Non-transferable.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cost', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChakraPointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(help_text='Signed integer: positive for earned, negative for redeemed')),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Points Earned'), ('REDEEMED', 'Points Redeemed')], default='EARNED', max_length=20)),
                ('activity_type', models.CharField(choices=[('WASTE_REPORT', 'Waste Report with Photo'), ('IMAGE_SCAN', 'AI Optical Waste Scan'), ('PICKUP_COMPLETED', 'Completed Waste Pickup'), ('STREAK_BONUS', 'Streak Milestone Bonus'), ('REWARD_REDEMPTION', 'Reward Redemption'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], default='WASTE_REPORT', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chakra_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_spent', models.PositiveIntegerField()),
                ('voucher_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Usable'), ('USED', 'Redeemed / Claimed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='accounts.rewardcatalogitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
