# Generated by Django 6.1 on 2026-09-13 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rewardcatalogitem_chakrapointtransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='Cleanup', max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('participants', models.PositiveIntegerField(default=0)),
                ('target_kg', models.PositiveIntegerField(default=0)),
                ('waste_recovered_kg', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('reward_points', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('OPEN', 'Open for Registration'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='chakrapointtransaction',
            name='activity_type',
            field=models.CharField(choices=[('WASTE_REPORT', 'Waste Report with Photo'), ('IMAGE_SCAN', 'AI Optical Waste Scan'), ('PICKUP_COMPLETED', 'Completed Waste Pickup'), ('COMMUNITY_CLEANUP', 'Community Cleanup Event'), ('STREAK_BONUS', 'Streak Milestone Bonus'), ('REWARD_REDEMPTION', 'Reward Redemption'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], default='WASTE_REPORT', max_length=30),
        ),
        migrations.CreateModel(
            name='CommunityEventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='accounts.communityevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
