# Generated by Django 6.1.1 on 2026-09-13 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_communityevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('gstin', models.CharField(blank=True, default='', max_length=50, verbose_name='GSTIN Number')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Dispatch Phone')),
                ('address', models.TextField(blank=True, default='', verbose_name='Primary Facility Address')),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=20)),
                ('industry_type', models.CharField(choices=[('CORPORATE', 'Corporate Office'), ('IT_PARK', 'IT / Tech Park'), ('MANUFACTURING', 'Manufacturing / Industrial'), ('HOTEL_HOSPITALITY', 'Hotel & Hospitality'), ('HOSPITAL', 'Hospital / Healthcare'), ('RETAIL_MALL', 'Retail & Mall'), ('EDUCATIONAL', 'Educational Institution'), ('OTHER', 'Other Enterprise')], default='CORPORATE', max_length=50)),
                ('epr_registered', models.BooleanField(default=True, verbose_name='EPR Registered')),
                ('is_verified', models.BooleanField(default=True, verbose_name='Verified Enterprise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
