# Generated by Django 6.1 on 2026-09-09 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_pct', models.FloatField()),
                ('combustibility_index', models.FloatField()),
                ('recyclability_score', models.FloatField()),
                ('rdf_suitability_score', models.FloatField()),
                ('contamination_pct', models.FloatField(default=0.0)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulated_reading', to='detection.wasteimage')),
            ],
        ),
    ]
