from django.db import models
from apps.detection.models import WasteImage


class SimulatedReading(models.Model):
    """Virtually generated feature values — NOT from a physical sensor.
    Generated by apps/analysis/services.py based on material type
    (+ realistic variation/noise or manual slider values)."""
    image = models.OneToOneField(
        WasteImage,
        on_delete=models.CASCADE,
        related_name="simulated_reading",
        null=True,
        blank=True,
    )
    moisture_pct = models.FloatField()          # 0-100 (virtual)
    combustibility_index = models.FloatField()  # 0-1 (virtual)
    recyclability_score = models.FloatField()   # 0-1 (virtual)
    rdf_suitability_score = models.FloatField() # 0-1 (virtual)
    contamination_pct = models.FloatField(default=0.0)
    is_manual_override = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Reading(Moisture: {self.moisture_pct}%, Recyclability: {self.recyclability_score}) - {self.id}"
