# Generated by Django 6.1 on 2026-09-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recyclability_threshold', models.FloatField(default=0.65)),
                ('contamination_threshold', models.FloatField(default=30.0)),
                ('combustibility_threshold', models.FloatField(default=0.55)),
                ('rdf_threshold', models.FloatField(default=0.5)),
                ('moisture_bio_threshold', models.FloatField(default=55.0)),
                ('low_confidence_threshold', models.FloatField(default=0.4)),
                ('decision_mode', models.CharField(choices=[('rule', 'Rule-based'), ('weighted', 'Weighted'), ('hybrid', 'Hybrid')], default='hybrid', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
